version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sivasankar@2003
      MYSQL_DATABASE: agriculture1
    ports:
      - "3306:3306"
    networks:
      - backend-network

  app:
    build:
      context: .
    container_name: backend_app
    depends_on:
      - mysql
    environment:
      ENV: docker
    networks:
      - backend-network
    ports:
      - "5050:5050"

networks:
  backend-network:
    driver: bridge
